# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - tekton_run: kubeflow/metadata/test/pipeline-runs/go-tests-run.yaml 
    name: go-unittests
